textureCoordArray[indx] = textureCoords[0]
textureCoordArray[indx+1] = textureCoords[1]
textureCoordArray[indx+2] = textureCoords[2]
textureCoordArray[indx+3] = textureCoords[3]
textureCoordArray[indx+4] = textureCoords[0]
textureCoordArray[indx+5] = textureCoords[3]

textureCoordArray[indx+6] = textureCoords[0]
textureCoordArray[indx+7] = textureCoords[1]
textureCoordArray[indx+8] = textureCoords[2]
textureCoordArray[indx+9] = textureCoords[3]
textureCoordArray[indx+10] = textureCoords[2]
textureCoordArray[indx+11] = textureCoords[1]
